#!/bin/sh

if [ ! -e $HOME/.vim/bundle/neobundle.vim ]; then
  curl https://raw.githubusercontent.com/Shougo/neobundle.vim/master/bin/install.sh > install.sh
  sh ./install.sh
  rm install.sh
fi
vim +NeoBundleInstall +qa

if [ ! -e $HOME/.tmux/plugins/tpm ]; then
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

if [ ! -e $HOME/.zsh/plugins/zsh-autosuggestions ]; then
  git clone https://github.com/tarruda/zsh-autosuggestions.git $HOME/.zsh/plugins/zsh-autosuggestions
fi

if [ ! -e $HOME/.zsh/plugins/zsh-history-substring-search ]; then
  git clone https://github.com/zsh-users/zsh-history-substring-search.git $HOME/.zsh/plugins/zsh-history-substring-search
fi

if [ ! -e $HOME/.zsh/plugins/zsh-syntax-highlighting ]; then
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $HOME/.zsh/plugins/zsh-syntax-highlighting
fi
